server:
  port: 8080
---
debug: true
spring:
  profiles: default
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: root
  redis:
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.mintit.bos.auth.model
server:
  port: 9090
